---
# ansible playbook for github.com/dschier-wtd/fedora-homeserver

- name: "Configure Fedora Homeserver"
  hosts: "all"

  vars_files:
    - "../manifest.yml"

  tasks:

    # Hostname
    - name: "Configure hostname"
      ansible.builtin.hostname:
        name: "{{ system.hostname }}"
      become: true

    # Time
    - name: "Configure timezone"
      community.general.timezone:
        name: "{{ system.timezone }}"
      become: true

    - name: "Manage chrony Packages"
      ansible.builtin.package:
        name: "chrony"
        state: "present"
      become: true

    - name: "Manage chrony Services"
      ansible.builtin.service:
        name: "chronyd.service"
        state: "started"
        enabled: true
      become: true

    # Core Packages
    - name: "Manage cli Packages"
      ansible.builtin.package:
        name:
          - "bash"
          - "bash-completion"
          - "curl"
          - "tmux"
          - "wget"
          - "vim"
        state: "present"
      become: true

    # SELinux
    - name: "Manage SELinux Packages"
      ansible.builtin.package:
        name:
          - "libselinux"
          - "libselinux-utils"
          - "setroubleshoot-server"
        state: "present"
      become: true

    - name: "Manage SELinux Configuration"
      ansible.posix.selinux:
        policy: "targeted"
        state: "enforcing"
      become: true

    # Firewall
    - name: "Manage firewalld Packages"
      ansible.builtin.package:
        name: "firewalld"
        state: "present"
      become: true

    - name: "Manage firewalld Services"
      ansible.builtin.service:
        name: "firewalld.service"
        state: "started"
        enabled: true
      become: true

    # Tuned / Power Saving
    - name: "Manage tuned Packages"
      ansible.builtin.package:
        name: "tuned"
        state: "present"
      become: true

    - name: "Manage tuned Service"
      ansible.builtin.service:
        name: "tuned.service"
        state: "started"
        enabled: true
      become: true
...
