---
# ansible/playbooks/deploy_pihole_container.yml

- name: "Deploy pihole Container"
  hosts: "all"

  vars:
    pihole_net_name: "pihole"
    pihole_app_image_name: "docker.io/pihole/pihole"
    pihole_app_image_tag: "latest"
    pihole_publish_http: "80"
    pihole_publish_dnsu: "192.168.178.80:53"
    pihole_publish_dnst: "192.168.178.80:53"
    pihole_admin_pass: "secure_password"

  tasks:

    - name: "Create pihole Podman Network"
      containers.podman.podman_network:
        name: "{{ pihole_net_name }}"
        state: "present"
      become: true

    ## Application

    - name: "Pull pihole-app Image"
      containers.podman.podman_image:
        name: "{{ pihole_app_image_name }}"
        tag: "{{ pihole_app_image_tag }}"
        state: "present"
      become: true

    - name: "Create pihole-app Service File"
      ansible.builtin.template:
        src: "container-pihole-app.service.j2"
        dest: "/etc/systemd/system/container-pihole-app.service"
        owner: "root"
        group: "root"
        mode: 0644
      become: true

    - name: "Start & Enable pihole-app Service"
      ansible.builtin.systemd:
        name: "container-pihole-app.service"
        state: "started"
        enabled: true
        daemon_reload: true
      become: true
...
